### ISSUE TITLE
Why is Addressable so heavy on memory?

### ISSUE THREAD

**Issue by ghost** [sporkmonger/addressable#14]
Hey,

I'm using a lib that requires addressable and I was really surprised when trying to reduce the memory footprint to see that Addressable eats about 4.8MB of memory when required!
Check these little snippets : http://gist.github.com/495292
As you can see the "uri" is roughly 0.5M, and even ActiveSupport (which is considered as heavy) is twice as light as Addressable.

I also wrote a small app that just parses URI, sleeps 10 and parses another URI (http://gist.github.com/495355) and used memprof to profile it, so it can certainly help reduce the footprint :  http://www.memprof.com/dump/4c5064e17fdeb66269000001 

Looks like addressable-2.1.2/lib/addressable/idna.rb is the place to look into!

Let me know if you can improve the whole thing... because 5MB is a LOT of memory these days for  a single requirement =D

**Comment by arthurnn** [comment]
was this ever addressed? I see 4.4MB of memory loaded by this gem

**Comment by dentarg** [comment]
@arthurnn Yes and no, since https://github.com/sporkmonger/addressable/commit/3db3329f02f675d45cccf45220de019f5d9391b5 (10 Apr 2011) you can use libidn (https://github.com/sporkmonger/addressable#install) that the first comment here talked about (https://github.com/sporkmonger/addressable/issues/14#issuecomment-331695). But for the pure Ruby version, nothing has really changed, it still loads the tables into memory when required.
