### ISSUE TITLE
Breaking change in #normalized_query

### ISSUE THREAD

**Issue by tylerhunt** [sporkmonger/addressable#176]
A breaking change was introduced in the latest patch-level release (2.3.6) here: https://github.com/sporkmonger/addressable/blob/master/lib/addressable/uri.rb#L1478

Previously, a query of `''` (empty string) would result in a `#normalized_query` return value of `''`, but it now results in `nil`. As a result, the return value of `#normalize` went from `…/path?` to `…/path`.

This became problematic for me when an upgrade of Webmock triggered Addressable to be upgraded, which in turn broke my test suite which uses VCR. The recorded VCR cassettes contained the trailing `?`, but the URIs it was comparing against no longer did since this change was made.

My issue here isn't with the change itself, but the fact that it was made as a patch release. This was a non-backwards-compatible change made, which should have been a minor release according to SemVer. This either slipped through when it shouldn't have, or Addressable isn't adhering to SemVer. Either way, it would be nice to have some clarification the policy here, and in the future handle this by properly incrementing the applicable segment of the version number (a transitional release with a deprecation warning would be even better).

**Comment by sporkmonger** [comment]
Addressable is kind of in a tough position generally because of the way people have added it as a dependency. Half of the Ruby ecosystem uses it, and a very sizable chunk of those dependency declarations have been made as `~> x.y.z`. Every time I make a minor release, as opposed to a patch release, half the Ruby ecosystem gets bundler errors do to a versioning conflict. Usually several versioning conflicts. I end up having to wrangle all the dependencies that have done an `~> x.y.z` dependency instead of `~> x.y` or `~> x.y, >=  x.y.z`, and usually there's a week or two involved in doing that.

I agree that this was non-backwards compatible and according to semver, technically should have gone in as 2.4.0. If the bulk of the dependencies on Addressable were set to assume semver, I would absolutely be releasing as semver, but so far I haven't been able to get people to declare sane dependencies.

My personal feeling is that every time someone writes a library that declares `~> x.y.z`, somewhere a kitten dies. It's 100% OK to write `~> x.y.z` for a Rails application. It is rarely OK to do that for a library unless you're talking about a 0.0.1 release.

That said, if people want me to adhere to semver, I will, along with a Wiki page on why all the :hankey: broke as a result.

**Comment by sporkmonger** [comment]
Actually, I went to cut 2.3.7 and noticed that Rubygems now drops warnings for the exact issue I raised above of badly declared dependencies. Given that development, I'm much more open to migrating to strict semver.

Don't worry, 2.3.7 contains no breaking changes. For reals.
