### ISSUE TITLE
Release, please!

### ISSUE THREAD

**Issue by sbleon** [sporkmonger/addressable#209]
Hi! I just had to switch to using `master` because the merged fix for https://github.com/sporkmonger/addressable/pull/174 hasn't been released yet. Can you get a patch release out sometime, please? Thanks!

**Comment by randoum** [comment]
Sorry to use the issue board for that, I was wondering too when you plan to release a new gem
Cheers

**Comment by patforna** [comment]
+1

**Comment by sporkmonger** [comment]
Hey sorry folks. I know I'm pretty behind on the library. I'll try to get to this soon.

**Comment by sporkmonger** [comment]
Sorry it still took me another two weeks, but I caught up on most of the outstanding pull requests and issues and I've cut a new release. Note that this release introduces some minor breaking changes (please see [CHANGELOG](https://github.com/sporkmonger/addressable/blob/master/CHANGELOG.md)), and so it's a minor release rather than a bugfix release.

**Comment by KitaitiMakoto** [comment]
@sporkmonger 
Thanks for your hard work!

**Comment by sbleon** [comment]
Thanks, @sporkmonger!
