### ISSUE TITLE
Why does `normalize` switches № to "No"?

### ISSUE THREAD

**Issue by PositiveAlex** [sporkmonger/addressable#217]
I faced with problem: 

When my url contains № , when I call `normalize`, it changes to *two symbols* N and o which is No. 

it's very strange to change one symbol to two symbols doing url completely different after that.

Try as example:

```
url = Addressable::URI.parse('http://example.com/')
url.query_values = [['param', '№']]
puts url
puts url.normalize
```

**Comment by sporkmonger** [comment]
Because IRIs are normalized with Unicode NFKC normalization. This converts visually ambiguous characters into their canonical forms, which in this case are the characters N and o. It's important to note that normalization is always optional in Addressable and can also be applied piece-wise to one component at a time.
