### ISSUE TITLE
Issue with Addressable::URI.encode

### ISSUE THREAD

**Issue by djberg96** [sporkmonger/addressable#241]
I don't seem to be getting back the expected result when attempting to encode a URL:

```
require 'addressable'

# Microsoft gives us a continuation URL that looks something like this:
url = "https://x.y.com/stuff/abc?api-version%3D2016-03-30%26%24skipToken%3Dabc123%2Bstuff%2Band%2FwU%3D"
uri = Addressable::URI.parse(url)

unencoded = Addressable::URI.unencode(uri)
puts unencoded

# I get expected result
# https://x.y.com/stuff/abc?api-version=2016-03-30&$skipToken=abc123+stuff+and/wU=

encoded = Addressable::URI.encode(unencoded)
puts encoded

# I do not get expected result. I get the same string again.
# https://x.y.com/stuff/abc?api-version=2016-03-30&$skipToken=abc123+stuff+and/wU=
```

**Comment by dentarg** [comment]
I'm sorry, but I believe you are expecting the wrong result. Addressable tries to follow [RFC 3986](https://tools.ietf.org/html/rfc3986) and your URI doesn't seem to contain any characters warranting percent encoding. See for yourself at https://github.com/sporkmonger/addressable/blob/addressable-2.4.0/lib/addressable/uri.rb.

**Comment by djberg96** [comment]
@dentarg But they do warrant decoding? I guess I just don't understand how things are supposed to work then.

**Comment by sporkmonger** [comment]
@dentarg is correct. The `unencode` method unencodes everything that's been encoded. The `encode` method only encodes things that it must encode, leaving everything else alone. It's also a little more lenient with respect to not encoding unnecessarily compared to many other URI libraries because it's context sensitive to the URI component any given character appears within. In this case, you should almost certainly not be encoding/unencoding the entire URI. Instead, encode/unencode the components independently. You can manually control the character classes that you want to encode explicitly by supplying an additional character class parameter.
