### ISSUE TITLE
Template won't match query params without values.

### ISSUE THREAD

**Issue by tpickett66** [sporkmonger/addressable#253]
I'm trying to extract values from urls that look like `http://example.com/foo/bar?no_value&some_value=baz`. The template I'm trying to use is `Addressable::Template.new('http://example.com/foo/bar{?no_value,some_value}'). But, when I try to `#extract` the source url I'm getting back `nil` instead of the expected hash. Interestingly `Addressable::URI#query_values` returns a reasonable hash: `{"no-value"=>nil, "some-value"=>"baz"}`.

Additionally, when I add an `=` after `no-value` but include nothing else the `Template` successfully extracts the query.

Repro code:
```ruby
require 'addressable/template'
template = Addressable::Template.new("http://example.com/foo/bar{?no_value,some_value}")
uri = Addressable::URI.parse('http://example.com/foo/bar?no_value&some_value=baz')
uri.query_values # => {"no_value"=>nil, "some_value"=>"baz"}
template.extract(uri) # => nil

uri = Addressable::URI.parse('http://example.com/foo/bar?no_value=&some_value=baz')
template.extract(uri) # => {"no_value"=>"", "some_value"=>"baz"}
```

**Comment by mimosa** [comment]
Addressable::Template not support DateTime: 
```ruby
require 'addressable/template'
template = Addressable::Template.new('http://example.com/foo/bar{?no_value,some_value}')
uri = Addressable::URI.parse('http://example.com/foo/bar?no_value&some_value=2017-03-10T00:00:00.000Z')
uri.query_values # => {'no_value'=>nil, 'some_value'=>'2017-03-10T00:00:00.000Z'}
template.extract(uri) # => nil

'2017-03-10'.to_time(:utc).to_s(:iso8601) # => '2017-03-10T00:00:00Z'

uri = Addressable::URI.parse('http://example.com/foo/bar?no_value=&some_value=2017-03-10')
template.extract(uri) # => {'no_value'=>'', 'some_value'=>'2017-03-10'}
```

**Comment by therabidbanana** [comment]
`template.extract` is intended to be a reverse of `template.expand`. Since no_value here is supposed to be nil, it is treated as the `undef` variable in expansions: (see https://tools.ietf.org/html/rfc6570#section-3.2.8). There is no valid expansion for a nil value that shows _just_ the name. 

Not all valid URIs are valid expansions of templates, and unfortunately there is no spec for how to handle expansion (it's not part of the RFC) so the best we can do is essentially reverse what happens with the expansion part of the code - if a URI is not a valid expansion, extraction can't work correctly.

DateTimes are treated as strings, as expansion is only defined for string, list and map (hash) values, but it is essentially the same problem - no_value in the first case is not a possible expansion. 
 
I think this issue is probably closable as it's working as expected @sporkmonger .

**Comment by therabidbanana** [comment]
@tpickett66 for your particular case, if you do wish to use template extract - perhaps you can use a dummy variable to handle the no_value case with something like:

    template = Addressable::Template.new('http://example.com/foo/bar?{ignore_me}{&some_value}')
    uri = Addressable::URI.parse('http://example.com/foo/bar?no_value&some_value=baz')
    uri.query_values # => {"no_value"=>nil, "some_value"=>"baz"}
    template.extract(uri) # => {"ignore_me"=>"no_value", "some_value"=>"baz"}
