### ISSUE TITLE
Examples of how addressable more closely conforms to RFC...

### ISSUE THREAD

**Issue by spnkr** [sporkmonger/addressable#313]
Would be great if there was more info on what "It more closely conforms to RFC..." means. e.g. what problems does this fix vs the standard ruby lib?

**Comment by dentarg** [comment]
That text in the README was last updated [over 6 years ago](https://github.com/sporkmonger/addressable/commit/43c448d125c0ae578c1991e0e964c1ef9b27bae0), since then, [`URI` in stdlib has been updated to "support RFC3986"](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/46491). So the situation might have changed.

[This comment from 2015 by @sporkmonger](https://github.com/sporkmonger/addressable/issues/161#issuecomment-87000114) has some discussion re: Ruby stdlib vs Addressable.

There are probably more discussions on the matter to be found in other issues here.

**Comment by mgrobelin** [comment]
Here are two examples where stdlib (ruby-2.5.1) doesn't behave (ipv6 address and username parsing):

[https://github.com/inspec/train/issues/110#issuecomment-303737460](https://github.com/inspec/train/issues/110#issuecomment-303737460)

**Comment by sporkmonger** [comment]
Note that @mgrobelin's IPv6 example is one that the stdlib is sort of getting right. Per the discussion @dentarg linked to above, I still wouldn't raise an exception, but that's not the correct way of expressing an IPv6 address in a URI. This is:

`ssh://pmuench@[2000:111b:ffe2:1:0:0:0:2]`

The stdlib is able to parse it without error once the square brackets are correctly included.

That said, to @spnkr's question, the text is much, much, much less true in recent Ruby's than it used to be and it would be totally fair to revise it.
