### ISSUE TITLE
Wrong normalization of ™ (due to the nkfc normalization)

### ISSUE THREAD

**Issue by ctrochalakis** [sporkmonger/addressable#325]
We have the following issue with url containing the `™` glyph.

```
$ bundle exec ruby  -r addressable -e 'puts Addressable::URI.parse("https://example.org/™.jpg").normalize.to_s'
https://example.org/TM.jpg
```

The issue here is that addressable uses `nfkc` which is a compatibility mode (the K in nfkc), so  `™` folds into `TM`, which is the wrong thing to do when normalizing unicode in urls.

We also had other issues in the past due to the forced `nfkc` with urls in `nfd` form.

**Comment by sporkmonger** [comment]
NFKC is correct. There's a number of reasons it was chosen, but one reason is actually that it has security implications. Characters in unicode that are visually very similar might otherwise be used in a phishing context to deceive users into believing they're on the correct site when a URL contains a homoglyph. The ™ symbol is maybe not the best example, but many others are virtually indistinguishable.
