### ISSUE TITLE
Feature: Adding more variables to an existing URI

### ISSUE THREAD

**Issue by myxoh** [sporkmonger/addressable#328]
**Use case:**
I have a template that generally describes an endpoint. Under certain circumstances (say, the right permissions), the endpoint accepts additional attributes. When that's the case I'd like to be able to add the additional attributes without having to create a new template for every instance.

**Concrete example:** 
Link for obtaining discussions for a user:
`{ "href": "https://example.com/user{/id}/discussions{?by_date}" }`
Link for obtaining discussions for my own user account:
`{ "href": "https://example.com/user/36/discussions{?by_date,by_ranking}" }`

When it is my own user I can filter by date or ranking. 

Currently using Addressable templates I either need 2 templates (which seems wasteful) or I need to send useless params on the first case.

With the feature I'm proposing, I could start with template `user_discussions` and from there go to `my_discussions` by attaching the additional permissions.

**i.e**
`user_discussions = Addressable::Template.new('https://example.com/user{/id}/discussions{?by_date}')`
`my_discussions = user_discussions.partial_expand(id: 36).attach_variables('by_ranking')`

PR: https://github.com/sporkmonger/addressable/pull/327

**Comment by myxoh** [comment]
Could anyone take a look at this?
I need to know whether this is a feature you are interested in supporting.
I'm happy with an answer that's as short as: `we are not interested` or, `we are interested, I'll look into it later`

**Comment by therabidbanana** [comment]
Hi Nicolas,

I meant to comment on this but I got lost in other work - thanks for the bump!

I think the PR would probably need some changes as it only supports a limited subset of valid uri templates (I’m not sure it would do the “expected” thing for `{;hash*}` or `example.com{?foo}#weird?` though I imagine those are pretty contrived examples)

I’m curious what this approach to the problem offers over starting with a more complex template and using partial expands to remove vars - maybe the example you have in mind is more complicated, but unless I’m forgetting how this code works - seems like your example could be accomplished like:

```
base = "https://example.com/user{/id}/discussions{?by_date,by_ranking}"
mine = Addressable::Template.new(base).partial_expand(id: 36)
other = Addressable::Template.new(base).partial_expand(by_ranking: nil)
```

**Comment by therabidbanana** [comment]
I'm not sure I'm following the full use case you're describing - any chance you can show a more complete example of what you're trying to build? 

Overall, I think for this to get merged `attach_variable`, at minimum, would need to be renamed to `attach_query_variable` as it only works for query variables, while the URI template spec has a variety of different options - but it's still not clear what the value would be in bringing this in and maintaining it long term. 

Mainly I'm concerned about the implementation behaving in unexpected ways because this entire thing is, unfortunately, built on top of regexes (you were just following my bad code here, so not your fault). This has already bit us a bit with some of the other features (most recently partial expand).
 
I think the ideal implementation, if I were to rebuild this from scratch, would be to properly tokenize a given URI Template so you could introspect the parsed version and easily add a variable to the variable list (and then serialize the new template). That'd be a pretty major change and not one I'm ready to take on right now though.

**Comment by myxoh** [comment]
First I agree and understand what are the risks involved (and that tokenizing would be the ideal, but far more complex, approach).
Also, more than happy to address any requested changes on the PR if you want to make them.

Here's the full user journey. 
On our systems, an admin can use our framework, and is able to configure their APIs and add additional resources.
Our front-end journeys are consuming our APIs with a HAL client that automatically parses and understands things like query params.

Because our APIs are configurable, I cannot construct at load time the full template including all variables because I don't have that information. I can, however, construct a partial template for some of our fixed APIs. For example, we have a thing called `services`. 
`https://example.com/user{/user_id}/services`
And we know that this collection is paginated:

`https://example.com/user{/user_id}/services{?page,per_page}`

But we don't yet know what are the filterable attributes. For example, if the user configured their services to have `mistery_point` or whatever variable name they choose, our APIs will be able to read a GET param `by_mistery_point=3` and filter services by that attribute.

Our problem is that `by_mistery_point` is not a text we can hard code somewhere, it is only known after the user configured the service, and can change at any point on runtime. 
So here lies our problem, we should be generating this template:

`https://example.com/user{/user_id}/services{?page,per_page,by_mistery_point}`

but we only know the original template. 

Of course, I'd understand it if you think this is enough of a niche problem, I already have the code to solve it, I just would much rather upstream it than just patch it :grinning: 

I'm also happy if you want to go the other way, and think I should try and be more general (open to suggestions as to how here).

**Comment by myxoh** [comment]
I'll address the secondary use case here. 
Being a maintainer of `grape` ( https://github.com/ruby-grape/grape ).
A functionality I'm looking to implement is, when we are using `grape` and `roar` together, it'd be very neat if the HAL links could automatically produced by introspecting the declared parameters. In this scenario, the developers are creating their own endpoints, which I can produce a full route for, but I don't have an easy way of producing the relevant HAL link. 
Admittedly, this could also be solve in that particular project (the grape + roar project), but because it's manipulating addresses, I'd much rather it be kept on a gem specific for this purpose as is addressable.

**Comment by myxoh** [comment]
I completely understand if you want to close this issue and PR if you don't find either of the use cases relevant enough :smile:. Please let me know as soon as you can! 
Thank you

**Comment by myxoh** [comment]
Hi, any news here?

**Comment by therabidbanana** [comment]
Sorry for the slow response here - it fell off my radar in the crunch before the holiday break! Forgot about it until a coworker was talking about how it can be awful having to wait for open source contributions to get merged in and I had a bunch of guilt when I remembered this. 😰 

I might be wrong, but my feeling is this case isn't generalizable enough to be useful directly in Addressable::Template, which has mostly been focussed on expanding existing templates into URIs, rather than building them. 

Given the few different issues with `partial_expand` we've seen crop up (which steps over that line and builds a new template), I'd be hesitant to add more API surface for building templates without rethinking the building blocks to not be entirely regex-powered here. Happy to hear arguments otherwise or suggestions on how to make the regex-powered mess less error prone, but I'm going to go ahead an close out for now so you aren't left hanging.
