### ISSUE TITLE
query_values escaped after set

### ISSUE THREAD

**Issue by brauliobo** [sporkmonger/addressable#334]
`ids` parameter wasn't changed but is escaped just by setting `query_values`
```
[19] Agora: (main)> u=Addressable::URI.parse 'https://example.com/?ids=1,2,3'
=> #<Addressable::URI:0x2aaaada8aa70 URI:https://example.com/?ids=1,2,3>
[20] Agora: (main)> u.to_s
=> "https://example.com/?ids=1,2,3"
[21] Agora: (main)> u.query_values = u.query_values.merge blah: 5
=> {"ids"=>"1,2,3", :blah=>5}
[22] Agora: (main)> u.to_s
=> "https://example.com/?blah=5&ids=1%2C2%2C3"
```

**Comment by dentarg** [comment]
This is needed because query values can hold values that must be encoded, example:

```ruby
[14] pry(main)> uri = Addressable::URI.parse("https://example.com/?ids=1,2,3")
=> #<Addressable::URI:0x3ffb189ca13c URI:https://example.com/?ids=1,2,3>
[15] pry(main)> uri.query_values = uri.query_values.merge(blah: "#5")
=> {"ids"=>"1,2,3", :blah=>"#5"}
[16] pry(main)> uri.to_s
=> "https://example.com/?blah=%235&ids=1%2C2%2C3"
[17] pry(main)> uri.normalize.to_s
=> "https://example.com/?blah=%235&ids=1,2,3"
```

As you can see, with `#normalize`, you can display the URL as it was originally entered.

I think what `#query_values=` does is mimicking what web browsers do when you click submit on a `<form>` with the `method` set to `get`.

---

References:

* https://en.wikipedia.org/wiki/Query_string#Web_forms
* https://en.wikipedia.org/wiki/Query_string#URL_encoding
* https://en.wikipedia.org/wiki/Percent-encoding#The_application.2Fx-www-form-urlencoded_type
* https://github.com/sporkmonger/addressable/issues/17#issuecomment-482300
* https://github.com/sporkmonger/addressable/issues/114#issuecomment-16338080
