### ISSUE TITLE
Normalize introduces weird character substitutions.

### ISSUE THREAD

**Issue by midnight-wonderer** [sporkmonger/addressable#395]
I spent a day figuring out what going on with my program and eventually found something weird from `Addressable`.
Please have a look.

By running the following code
~~~ruby
::Addressable::URI.parse('http://example.com/%E0%B8%84%E0%B8%B3%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%B2%E0%B9%84%E0%B8%97%E0%B8%A2').normalize.to_s
~~~
I expect
~~~ruby
'http://example.com/%E0%B8%84%E0%B8%B3%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%B2%E0%B9%84%E0%B8%97%E0%B8%A2'
~~~
as an output.

However, the actual output is:
~~~ruby
'http://example.com/%E0%B8%84%E0%B9%8D%E0%B8%B2%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%B2%E0%B9%84%E0%B8%97%E0%B8%A2'
~~~
Please note the difference in length.

Upon a closer look `%E0%B8%B3` seems to be substituted with `%E0%B9%8D%E0%B8%B2` with no apparent reason.  
Since they are entirely different characters, the substitution does not work.

This is highly unexpected, and I'm not sure if it is the only case. (I only stumble upon one.)

P.S. version 2.7.0

**Comment by midnight-wonderer** [comment]
Digging further the behavior seems to be specified in https://unicode-org.github.io/cldr-staging/charts/37/supplemental/character_fallback_substitutions.html
more specifically, in the NFKC normalization flavor of Unicode standard.

For some context, substitute Thai character ำ with ํ and า is like substitute English character m with r and n, which mostly does not make sense, except they are somewhat look alike.  
Nobody uses ํ anymore in Thai; in fact, it takes me some time to locate the character on my keyboard.  
The only reason for such substitution is for security reasons.
Think, someone can create a seemingly legit domain name imposing as some other legit identities.

Why does Addressable use KC flavor for both domain part and path?  
By looking specifically at this case, KC (NFKC) flavor should be used only for the domain while NFC should be used everywhere else.
From what I read KC is mostly for security reasons, NFC for compatibility. [See FAQ](https://unicode.org/faq/normalization.html)

**Comment by sporkmonger** [comment]
It is indeed for security reasons. This is also why Addressable provides several different normalize functions, allowing piece-wise normalization. For your application, the correct thing to do might be to do piece-wise normalization rather than running normalization over the entire URI. Critically, normalization is not an appropriate step for all use-cases. The IRI specification, IIRC, does recommend that content-creators assign IRIs in a fully normalized format, including path components, though it doesn't explicitly specify NFC or NFKC. I believe the choice of NFKC vs NFC here to be somewhat arbitrary – neither is the right answer 100% of the time for every application. NFKC is better for use-cases with phishing or deception threat models, NFC is better for maintaining fidelity, and well, the un-normalized form is even better at that. At this point, ten years in, it doesn't make sense to make a change this drastic. I could be easily persuaded that normalization functions should allow you to choose the normalization form to apply, but the default can't be changed.
